server:
  port: 8028
  servlet:
    context-path: /admin

spring:
  profiles:
    active: @env@
  application:
    name: CMS
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.kangyonggan.cms.model
  config-location: classpath:mybatis.xml

mapper:
  mappers: com.kangyonggan.common.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
